import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'react-multi-carousel/lib/styles.css';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
import 'swiper/css';
import 'swiper/css/navigation'
import 'swiper/css/pagination'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conecta Peças",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Container>
          {children}
        </Container>
        </body>
    </html>
  );
}
